---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "fullname" . }}-auth
  labels:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
    userpass: "{{ .Values.security.username }}:{{ .Values.security.password }}"
